### ISSUE TITLE
Npm run start error

### ISSUE THREAD

**Issue by andysay** [silvestreh/feathers-nuxt#3]
[nuxt] Building done

> feathers-nuxt@0.0.0 start /Users/andreyleonov/Desktop/feathers-nuxt
> NODE_ENV=production node src/

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3030
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Function.listen (/Users/andreyleonov/Desktop/feathers-nuxt/node_modules/express/lib/application.js:618:24)
    at Function.listen (/Users/andreyleonov/Desktop/feathers-nuxt/node_modules/feathers/lib/application.js:155:30)
    at Function.listen (/Users/andreyleonov/Desktop/feathers-nuxt/node_modules/uberproto/lib/proto.js:30:17)
    at process.on (/Users/andreyleonov/Desktop/feathers-nuxt/src/index.js:14:22)
    at emitNone (events.js:105:13)
    at process.emit (events.js:207:7)
    at process.nextTick (/Users/andreyleonov/Desktop/feathers-nuxt/src/middleware/nuxt.js:15:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-nuxt@0.0.0 start: `NODE_ENV=production node src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-nuxt@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by bc96123** [comment]
how this issue solved? i also faced this issue

**Comment by silvestreh** [comment]
Error: listen EADDRINUSE :::3030 means you already have another process listening on port 3030. Change the port.

**Comment by silvestreh** [comment]
See https://github.com/silvestreh/feathers-nuxt/blob/master/config/default.json#L3
